// deltax-ui-v2/src/components/Meter.vue
<template> 
  <div class="flex flex-row items-stretch overflow-hidden | rounded-md border-2 border-blue-600" >
    <div class="w-1/3 py-1 px-2 bg-blue-600 text-white font-bold">
        {{name || topicname}}
    </div>   
      <div class="flex-grow auto-cols-max font-bold"> 
        <rt-value :topicName="topicName"></rt-value>
      </div> 
      <div class="py-1 px-2">
        {{unit || ""}}
      </div>
  </div> 
</template>
 
<script  >   
import RtValue from "./RtValue.vue";

export default {
  components:{
    RtValue
  },
  props: {
    name: {
      type: String,
    },
    topicName: { 
      require:true,
      type: String,
    },
    unit: {
      type: String,
    }
  },

  data() {
    return {  };
  }
}
</script>

// deltax-core-ui/src/Components/Meter.svelte
<svelte:options tag={"dx-meter"} />

<script >
    export let topicname;
    export let name;
    export let unit;
    export let color;

    if (!color)
        color = "gray";
    if(!name)
        name= "---";

</script>

<div class="grid overflow-hidden shadow-mb-xl bg-white hover:bg-gray-300 dark:bg-gray-800 dark:hover:bg-black"> 
    <div class="text-center flex-row self-center"> 
      <span class="text-5xl font-bold font-sans break-all text-{color}-700 dark:text-{color}-300 ">
        <dx-rt-value topicname={topicname}></dx-rt-value>
        </span>
        {#if unit }
            <span class="font-sans font-bold text-{color}-700 dark:text-{color}-300" >
            {unit}
            </span>
        {/if}
    </div>
    <div class="p-1 self-center text-center font-bold text-gray-800 dark:text-gray-300">
        {name}
    </div>
</div>
  
<style>
    @import "/global.css";
</style>
